### ISSUE TITLE
Questions about the codes for IMDB-BINARY 

### ISSUE THREAD

**Issue by Cecilia-Q725** [zhongyu1998/PG-GNN#2]
1. After entering the code “python main_tu.py --dataset IMDBBINARY --batch_size 16 --hidden_dim 16 --num_layers 5 --final_dropout 0.0 --graph_pooling_type sum --degree_as_tag --fold_idx <fold>” into the command line window of Pycharm, a warning is displayed saying that there is a syntax error in this code. I found that this code seems to be a collection of functions and file names, not instructions. When trying to run the main_tu.py file, I also encountered no functions that required the above constraints to be entered in order to run. So I don't quite understand what you meant by writing this sentence. Hope you can explain it to me.

2. Although main_tu.py can be run directly after downloading, I am very confused about the output of this code file. If possible, I would appreciate your tips so that I can better understand the inputs and outputs of the model.

3. According to the paper, the accuracy of this model is its accuracy in judging movie types by analysis the networks of actors and actresses. Theoretically, this model is based on the relationship between the nodes and edges of the graph, but because the data set of this model is too abstract, it is all numbers and vectors, so I have no idea how this model is established and which one I should refer to. If possible, I hope you can provide me with a description of the data and hints on the code.

4. I am considering using the PS-GNN model for practice. For example, social network analysis. But I haven't found any suitable data set yet. I would be sincerely grateful if you have any recommendations.

**Comment by zhongyu1998** [comment]
Thank you for your interest in our code.

A1 & A2.
According to Section 4.2 in our paper, "For TUDataset, we follow the same data split and evaluation protocol as Xu et al. [7]. We perform 10-fold cross-validation with random splitting and report our results (the average and standard deviation of testing accuracies) at the epoch with the best average accuracy across the 10 folds." For the command
```shell
python main_tu.py --dataset IMDBBINARY --batch_size 16 --hidden_dim 16 --num_layers 5 --final_dropout 0.0 --graph_pooling_type sum --degree_as_tag --fold_idx <fold>
```
our [instructions](../blob/main/README.md#imdb-binary) specify "where `<fold>` takes from 0 to 9" after the command. Here, `<fold>` denotes the fold index for performing 10-fold cross-validation and is a parameter to be provided. Therefore, the correct form of this command after instantiating `<fold>` should be:
```shell
python main_tu.py --dataset IMDBBINARY --batch_size 16 --hidden_dim 16 --num_layers 5 --final_dropout 0.0 --graph_pooling_type sum --degree_as_tag --fold_idx 0
```
$\vdots$
```shell
python main_tu.py --dataset IMDBBINARY --batch_size 16 --hidden_dim 16 --num_layers 5 --final_dropout 0.0 --graph_pooling_type sum --degree_as_tag --fold_idx 9
```
As described above, by taking `<fold>` from 0 to 9 and executing a total of 10 times, we output the final result at the epoch with the best average accuracy across the 10 folds.

A3.
I will first explain the meaning of file [`IMDBBINARY.txt`](../blob/main/dataset/IMDBBINARY/IMDBBINARY.txt) using the IMDB-BINARY dataset as an example. For each graph (e.g., Lines 2-22; Lines 23-55), column 1 in the initial line (e.g., Line 2; Line 23) represents the number of nodes in the graph, and column 2 represents the graph label. In subsequent lines (e.g., Lines 3-22; Lines 24-55), each line represents a node, where column 1 represents the node feature of the current node, column 2 represents the number of neighbors of the current node, and columns 3 and beyond represent the neighbors of the current node. However, node features are not provided for social networks (e.g., IMDB-B, IMDB-M, and COLLAB), and thus, they are set to zeros in column 1.

Regarding our proposed model PG-GNN, the core idea is to use a permutation-sensitive function (e.g., LSTM) to explicitly model the relationships among neighboring nodes. This process can be formalized as Eq. (4) in our paper, illustrated in Appendix J.1 and Figure 8 in our appendix, and corresponds to Lines 67-126 in our code [`groupcnn.py`](../blob/main/models/groupcnn.py).

A4.
You can find more information on the TUDataset (www.graphlearning.io). There are over 20 datasets related to social networks on the TUDataset (see https://chrsmrrs.github.io/datasets/docs/datasets/ for details), as well as various other types of datasets. I believe you will find datasets that align with your requirements.
